version: "3"
services:
  db-postgres:
    image: "postgres:11.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "selfdev-jpa"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "SQL"